events {}

http {

    upstream auth_service {
        server auth-service:5000;
    }

    upstream product_service {
        server product-service:5001;
    }

    server {

        listen 80;

        location /api/auth/ {
            proxy_pass http://auth_service;
        }

        location /api/products {
            proxy_pass http://product_service;
        }

        location / {
            return 200 'API Gateway Running';
            add_header Content-Type text/plain;
        }
    }
}